### ISSUE TITLE
2021 lectures links are down

### ISSUE THREAD

**Issue by ricalessandri** [Martini-Force-Field-Initiative/Martini-Force-Field-Initiative.github.io#19]
hi there, I've finally setup the quarto extension for VS Code (thanks @Lp0lp!) and started to take a close look at the new website and it's looking nicer and nicer - awesome feat @danielpastor97 et al.!

One thing I noticed while browsing the new website now is that the lectures at the links:
http://cgmartini.nl/index.php/2021-martini-online-workshop/lectures
are down !!
Don't remember who uploaded them on Youtube (perhaps @P-Vainikka?) but we should fix that... I have my own lecture still on my laptop and hopefully we can find all the other lectures, too.

I plan on reviewing more things as I find the time.

**Comment by AlexHdeVriesMDGroup** [comment]
As I wrote in the email (sorry I did not use Github, I am not all that active on Github in general), all .mp4 files of the 2021 online workshop are on our internal disk server. In total 1.6 G of zipped files. 

I can help transfer them elsewhere by allowing (temporary) access or in some other way that we can figure out together. 

Let me know! (probably best to write me an email...)

Alex de Vries

**Comment by danielpastor97** [comment]
Hi @AlexHdeVriesMDGroup, thanks for shedding some light on this. As I mentioned in the email, I will try to host the videos using CloudFront (aws service) to maintain consistency. As soon as I have the files in my hands, I will give it a try.

**Comment by danielpastor97** [comment]
Hi @AlexHdeVriesMDGroup and @ricalessandri , I managed to provide access to the video files through aws cloudfront inside the website. Now that everything is fully centralized, we do not rely on any other services other than our aws set-up. I will merge the PR with the changes, which will close this issue and update the changes on the website (temporarily at https://martini-force-field-initiative.github.io/ ). Thanks both for your contribution on this.
