### ISSUE TITLE
 Lecture Powerpoints unavailable 

### ISSUE THREAD

**Issue by chelsea-brown** [Martini-Force-Field-Initiative/Martini-Force-Field-Initiative.github.io#26]
I know there are issues with the Youtube videos, but I am not sure if you are aware that the slides for all of the lectures are not available.

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>WA74QBS23DHTWS3Y</RequestId>
<HostId>LvRs5+tG3+XXN68MLG6pEZ1FKQ1rJBKc0lI2kakVLSGLMp+6jp/atvqSdDEWqoIiQFzaO1lQLWA=</HostId>
</Error>

**Comment by danielpastor97** [comment]
Hi @chelsea-brown , I am fixing the issue with the videos now and I needed to modify the path to the pdfs. I am already deploying a version where both things should be working okay. Can you please check in 15 minutes from now and let me know?

**Comment by danielpastor97** [comment]
@chelsea-brown I just checked and everything on the Lectures page, including presentations and videos, is working perfectly now. I will move on to close this issue. Thanks a lot!

**Comment by danielpastor97** [comment]
@chelsea-brown I just checked and everything on the Lectures page, including presentations and videos, is working perfectly now. I will move on to close this issue. Thanks a lot!
